apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  labels:
    app: nextcloud
  namespace: nextcloud
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
  POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
