apiVersion: v1
kind: Service
metadata:
  name: postgres-nc-svc
  namespace: nextcloud
  labels:
    app: postgres-nc
spec:
  selector:
    app: postgres-nc
  ports:
    - protocol: TCP
      name: postgres
      port: 5432
      targetPort: 5432
