apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-nc
  namespace: nextcloud
spec:
  serviceName: "redis-service"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        - name: init-redis
          image: redis:latest
          command:
            - bash
            - "-c"
            - |
              set -ex
              cp /mnt/redis-config.conf /etc/redis-config.conf

          volumeMounts:
            - name: redis-claim
              mountPath: /etc
            - name: redis-config
              mountPath: /mnt/
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: redis-nc
          command:
            - redis-server
            - "/etc/redis-config.conf"
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-claim
              mountPath: /etc
      volumes:
        - name: redis-config
          secret:
            secretName: redis-secret
  volumeClaimTemplates:
    - metadata:
        name: redis-claim
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 1Gi
